version: '2'
services:
# DB
  mysql:
    container_name: "lamp_mysql"
    image: mysql:5.6
    ports:
      - '3309:3306'
    extends:
      file: ./mysql/password.yml
      service: password
    volumes:
      - ./mysql/datastore:/var/lib/mysql
# nginx
  nginx:
    container_name: "lamp_nginx"
    image: nginx:1.11
    links:
      - mysql
      - php
# php
  php:
    container_name: "lamp_php"
    image: php:7.1-apache
    ports:
      - '1111:80'
    volumes:
      - ./html:/var/www/html
      - ./log/apache:/var/log/apache2
    links:
      - mysql
